"""
IndexerService — writes materialized files and maintains the .cortex/index.md.
"""

import os
import re

import yaml

from ...config.logfire_config import get_logger

logger = get_logger(__name__)

KNOWLEDGE_DIR = ".cortex/knowledge"
INDEX_FILE = ".cortex/index.md"


class IndexerService:
    def slugify_topic(self, topic: str) -> str:
        slug = topic.lower().strip()
        slug = re.sub(r"[^a-z0-9\s-]", "", slug)
        slug = re.sub(r"[\s]+", "-", slug)
        slug = re.sub(r"-+", "-", slug)
        return slug.strip("-")

    def generate_unique_filename(self, project_path: str, topic: str) -> str:
        slug = self.slugify_topic(topic)
        knowledge_dir = os.path.join(project_path, KNOWLEDGE_DIR)
        filename = f"{slug}.md"
        counter = 2
        while os.path.exists(os.path.join(knowledge_dir, filename)):
            filename = f"{slug}-{counter}.md"
            counter += 1
        return filename

    async def write_materialized_file(self, project_path: str, filename: str, content: str) -> str:
        knowledge_dir = os.path.join(project_path, KNOWLEDGE_DIR)
        os.makedirs(knowledge_dir, exist_ok=True)
        file_path = os.path.join(knowledge_dir, filename)
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Wrote materialized file | path={file_path}")
        return file_path

    async def remove_file(self, project_path: str, filename: str) -> None:
        file_path = os.path.join(project_path, KNOWLEDGE_DIR, filename)
        if os.path.exists(file_path):
            os.remove(file_path)
            logger.info(f"Removed materialized file | path={file_path}")

    async def update_index(self, project_path: str) -> None:
        knowledge_dir = os.path.join(project_path, KNOWLEDGE_DIR)
        cortex_dir = os.path.join(project_path, ".cortex")
        os.makedirs(cortex_dir, exist_ok=True)

        entries = []
        if os.path.isdir(knowledge_dir):
            for filename in sorted(os.listdir(knowledge_dir)):
                if not filename.endswith(".md"):
                    continue
                file_path = os.path.join(knowledge_dir, filename)
                meta = self._extract_frontmatter(file_path)
                topic = meta.get("topic", filename.replace(".md", "").replace("-", " ").title())
                date = meta.get("materialized_at", "unknown")
                urls = meta.get("original_urls", meta.get("source_urls", []))
                source_str = ", ".join(urls) if urls else "local"
                if isinstance(date, str) and "T" in date:
                    date = date.split("T")[0]
                entries.append(f"- [{topic}](knowledge/{filename}) — {date} — from {source_str}")

        lines = [
            "# .cortex Knowledge Index",
            "",
            "Auto-generated by Cortex. Do not edit manually.",
            "",
        ]
        if entries:
            lines.append("## Materialized Knowledge")
            lines.append("")
            lines.extend(entries)
        else:
            lines.append("No materialized knowledge files yet.")
        lines.append("")

        index_path = os.path.join(cortex_dir, "index.md")
        with open(index_path, "w") as f:
            f.write("\n".join(lines))
        logger.info(f"Updated index | path={index_path} | entries={len(entries)}")

    def _extract_frontmatter(self, file_path: str) -> dict:
        try:
            with open(file_path) as f:
                content = f.read()
            if content.startswith("---"):
                parts = content.split("---", 2)
                if len(parts) >= 3:
                    return yaml.safe_load(parts[1]) or {}
        except Exception:
            pass
        return {}
